apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-system-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: 8.130.108.60 # 替换成你的域名或 IP
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: transaction-system
                port:
                  number: 80
